Roboflow: 1 #If dataset from Roboflow -> 0 else 1

dataset:
  workspace_name: huyifei
  project_name: dog-cat
  project_version: 1
  model: yolov11

datasetCustom:
  PredictionPath: C:/Git_Repos/blueprint-object-detection/data/dog-cat/test/images #Folder with images for prediction
  PredictionSavePath: C:/Git_Repos/blueprint-object-detection/result #Path where predictions should be saved
  ImageType: jpg #Type of images in the folder

model:
  modelName: yolo11n.pt
  modelMode: train #train, predict, train_predict
  modelConfidence: 0.4 #Used for predict and train_predict

modelParams:
  epochs: 1
  imgsz: 640
  patience: 100
  batch: 8
  optimizer: AdamW #SGD, Adam, AdamW, NAdam, RAdam, RMWProp, auto
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  dropout: 0.0
  plots: True
  project: C:/Git_Repos/blueprint-object-detection/runs #Directory where metrics, weights, etc. are saved
