dataset:
  workspace_name: huyifei
  project_name: tft-id
  project_version: 1
  model: yolov11

modelName: yolo11n.pt

modelMode: train #train, predict, train_predict
modelConfidence: 0.1 #Used for predict and train_predict

modelSpecific:
  epochs: 1
  imgsz: 640
  patience: 100
  batch: 8
  optimizer: AdamW #SGD, Adam, AdamW, NAdam, RAdam, RMWProp, auto
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  dropout: 0.0
  project: C:\Git_Repos\blueprint-object-detection\runs #Directory where metrics, weights, etc. are saved
